don't allow null values in ConcurrentArrayList
because that can be the only reason for the CI failure I saw:

ERROR: FAIL java.lang.NullPointerException java.lang.NullPointerException ------------------------------
java.lang.NullPointerException
	at org.h2.mvstore.MVMap.openVersion(MVMap.java:1095)
	at org.h2.test.store.TestConcurrent.testConcurrentChangeAndGetVersion(TestConcurrent.java:346)
	at org.h2.test.store.TestConcurrent.test(TestConcurrent.java:56)
	at org.h2.test.TestBase.runTest(TestBase.java:142)
	at org.h2.test.TestAll.addTest(TestAll.java:990)
	at org.h2.test.TestAll.testUnit(TestAll.java:960)
	at org.h2.test.TestAll.runTests(TestAll.java:625)
	at org.h2.test.TestAll.testAll(TestAll.java:563)
	at org.h2.test.TestAll.run(TestAll.java:512)
	at org.h2.test.TestAll.main(TestAll.java:452)